### ISSUE TITLE
Move to a new hosting platform

### ISSUE THREAD

**Issue by sunjunkie** [anitab-org/powerup-scenario-builder#16]
## Description
Currently the Powerup Scenario Builder example live app is hosted on Rawgit. This platform is shutting down so the example app must be hosted on a different platform. See [Rawgit home page.](https://rawgit.com/)

### Update [Required]
- [ ] Update the project so that the sample live app is hosted on a supported platform.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

**Comment by dhuang612** [comment]
Hi,

I used this service:
https://surge.sh/
 and hosted this project here:
https://powerup-scenario.surge.sh/

Does this work?
